name: CI

on:
  pull_request:
    branches:
      - develop
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4
      
      - name: Intalar o Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar as dependencias
        run: npm install

      - name: Rodar os testes
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4
      
      - name: Intalar o Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar as dependencias
        run: npm install

      - name: Rodar o build
        run: npm run build